# Personal info (fill as needed)
name: Ethan Greene
title: Data Scientist & Software Engineer
email: greeneed@g.cofc.edu
phone: (843) 460 - 3511

# About Section
about_profile_image: assets/img/headshot.jpg
about_content: >
  Passionate computer scientist focused on data science and software development.

  Skilled in Java, Python, SQL, PHP, C, and Small Language Model Fine-tuning.

  ## Technical Skills

  - **Languages:** Java, Python, SQL, PHP, C  
  - **Machine Learning:** Small Language Model Fine-tuning, PCA, KNN  
  - **Web Development:** PHP, MySQL, Session Management, Form Handling  
  - **Tools:** Hugging Face Transformers, Selenium, Pandas
  - **Methodologies:** Agile, Scrum
