# _config.yml
title: Ethan Greene
description: >
  Hi, I’m Ethan. ...
logo: /assets/img/headshot.jpg
theme: jekyll-theme-minimal

# Add this line
markdown: kramdown
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
sass:
  style: compressed
include:
  - assets/css
