title: Ethan Greene
description: >
  Hi, I’m Ethan. This site highlights my projects and accomplishments in computer science — feel free to reach out at greeneed@g.cofc.edu or (843) 460-3511. 
  Connect with me on LinkedIn: https://linkedin.com/in/ethan-greene
show_downloads: true
logo: /assets/img/headshot.jpg
theme: jekyll-theme-minimal
