title: Ethan Greene
description: Hi I'm Ethan and this website serves as a look into some of the accomplishments I have made in my academic career.
show_downloads: true
logo: /assets/img/headshot.jpg
theme: jekyll-theme-minimal
