title: Ethan Greene
description: >
  Hi, I’m Ethan. This site highlights my projects and accomplishments in computer science — feel free to reach out at greeneed@g.cofc.edu or (843) 460-3511.

  Connect with me on LinkedIn: www.linkedin.com/in/ethan-greene-b08a87205
logo: /assets/img/headshot.jpg
remote_theme: sproogen/modern-resume-theme  # or whichever one you choose
plugins:
  - jekyll-remote-theme
