title: Ethan Greene
description: Hi, I’m Ethan — welcome to my portfolio.
This site showcases some of the projects and accomplishments I’ve worked on throughout my career in computer science. From machine learning experiments to web applications, you’ll find examples of the skills and technologies I’ve used to build and learn.

Feel free to reach out!
📧 greeneed@g.cofc.edu
📞 (843) 460-3511
show_downloads: true
logo: /assets/img/headshot.jpg
theme: jekyll-theme-minimal
