title: Ethan Greene
description: Computer Scientist
email: greeneed@g.cofc.edu
phone: "(843) 460-3511"
location: Charleston, SC
linkedin_username: ethan-greene-b08a87205
github_username: Greene-Ethan
avatar: /assets/img/headshot.jpg

remote_theme: sproogen/modern-resume-theme
plugins:
  - jekyll-remote-theme
